<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelErrorMessage</name>
   <tag></tag>
   <elementGuidId>f19b2bae-fc05-4166-982a-16a2b4091bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginModal']/div/div/div[2]/div/form/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.login__error.alert.alert-danger.text-sm.text-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>90f4d8c2-b927-4429-9bf9-2dfc22c506a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login__error alert alert-danger text-sm text-center</value>
      <webElementGuid>17817a54-b9a0-4629-a2db-1a8f7d9405f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your Enterpriser ID or Password is incorrect (2).</value>
      <webElementGuid>2187e5df-a4e0-4e54-83e7-42a4e5c5c8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content modal-content--rounded&quot;]/div[@class=&quot;modal-body modal-section--cleaned&quot;]/div[@class=&quot;modal-section__content&quot;]/form[@class=&quot;js-login-form&quot;]/div[@class=&quot;login__error alert alert-danger text-sm text-center&quot;]</value>
      <webElementGuid>a4a9badc-fa0b-4222-adc8-a70fcf55e43f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginModal']/div/div/div[2]/div/form/div[2]</value>
      <webElementGuid>879ed462-f769-4bfb-8416-7c824f64e667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use the country code on your Enterpriser ID. Example: I0123456A'])[1]/following::div[1]</value>
      <webElementGuid>0c22fb97-f560-4510-8c38-7774fb133ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[4]</value>
      <webElementGuid>808c8139-59d9-49da-b9cd-426beda981f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterpriser ID'])[1]/preceding::div[1]</value>
      <webElementGuid>4c574a70-079e-4af1-9b40-274310bdbf7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::div[2]</value>
      <webElementGuid>3206f4f8-0742-499f-bc9f-0da56c63fc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your Enterpriser ID or Password is incorrect (2).']/parent::*</value>
      <webElementGuid>7b342f4e-48a4-4fad-85e5-eff7602a6c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>974a8ca3-6293-4125-9222-4bbf86e87413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your Enterpriser ID or Password is incorrect (2).' or . = 'Your Enterpriser ID or Password is incorrect (2).')]</value>
      <webElementGuid>169a1939-0a26-445f-8965-37128c902cd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
